name: news_app
description: News App
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17+1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  injectable: ^2.3.0
  logging: ^1.2.0
  flutter_svg: ^2.0.7
  flutter_sliding_tutorial: ^2.0.0+1
  flutter_verification_code: ^1.1.6
  blur: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.5
  dart_code_metrics_presets: ^1.8.0
  flutter_lints: ^2.0.0
  
  injectable_generator: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets: 
    - assets/newspaper-fill1.svg
    - assets/google.svg
    - assets/facebook.svg
    - assets/envelope.svg
    - assets/lock.svg
    - assets/user.svg
    - assets/followFacebook.svg
    - assets/followPinterest.svg
    - assets/followLinkedin.svg
    - assets/followReddit.svg
    - assets/followTwitter.svg
    - assets/followWhatsapp.svg
    - assets/bookmarkMiniGray.svg
    - assets/bookmarkMiniBlue.svg
    - assets/share.svg
    - assets/eyeGray.svg
    - assets/eyeBlue.svg
    - assets/chatCircleGray.svg
    - assets/chatCircleBlue.svg
    - assets/drawerBookmark.svg
    - assets/drawerFlagUSA.svg
    - assets/drawerHeadset.svg
    - assets/drawerNotepad.svg
    - assets/drawerPencilLine.svg
    - assets/drawerSignOut.svg
    - assets/drawerStar.svg
    - assets/drawerSun.svg
    - assets/search.svg
    - assets/categoryHandShake.svg
    - assets/categoryBug.svg
    - assets/categoryBugDroid.svg
    - assets/categoryBuildings.svg
    - assets/categoryCamera.svg
    - assets/categoryCoffee.svg
    - assets/categoryCreditCard.svg
    - assets/categoryForkKnife.svg
    - assets/categoryHandshake(blue).svg
    - assets/categoryHeartbeat.svg
    - assets/categoryNotepad.svg
    - assets/categoryPenNib.svg
    - assets/images/Illustration1.png
    - assets/images/Illustration2.png
    - assets/images/Illustration3.png
    - assets/images/DotActive.png
    - assets/images/DotInactive.png
    - assets/images/Security.png
    - assets/images/Security1.png